package com.euler;

/**
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 */
import java.util.ArrayList;
import java.util.List;

public class Problem44 {

	public static void main(String[] args) {
		List<Integer> list = new ArrayList<Integer>();
		for (int i = 0; i < 10000; i++)
			list.add(i * ((3 * i) - 1) / 2);

		loop: for (int i = 1; i < list.size(); i++)
			for (int j = i + 1; j < list.size(); j++)
				if ((list.indexOf(list.get(i) + list.get(j)) != -1)
						&& (list.indexOf(list.get(j) - list.get(i)) != -1)) {
					System.out.println("i -> " + i + " j-> " + j + " " + (list.get(j) - list.get(i)));
					break loop;
				}

	}
}
